version: '3.9'
services:
  nest-sgr-api:
    container_name: nest-sgr-api
    command: bash -c "npm install && npx prisma generate && npx prisma db push"
    env_file:
      - .env
    restart: always
    working_dir: /usr/src/sgr-backend
    volumes:
      - ./dist/:/usr/src/sgr-backend/dist
      - ./package.json:/usr/src/sgr-backend/package.json
      - ./prisma:/usr/src/sgr-backend/prisma
    image: node:16
    ports:
      - "3000:3000"
    links:
      - mysql-sgr

  mysql-sgr:
    container_name: mysql-sgr
    image: mysql:latest
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sgr
